### ISSUE TITLE
Installation error (cannot find -lreactionThermophysicalModelsGCFOAM)

### ISSUE THREAD

**Issue by AnzarMark2** [GeoChemFoam/GeoChemFoam#27]
Hello,

I am facing an error while compiling.

![image](https://github.com/GeoChemFoam/GeoChemFoam/assets/93387663/e585a460-11fe-44eb-81f8-765cf1c97464)

**Comment by julienmaes** [comment]
Hi Mark,

Yes, we've seen this error previously, Phreeqc doesn't compile with the newest compiler. Replace l1 by *l1 and it should work

**Comment by AnzarMark2** [comment]
Thank you.

The compilation was successful. I did it with gcc 11.2.0.
